import assert from 'assert';
import { DbType, Statement, SqlCommand } from 'lubejs';
import { adapter, getProvider } from '../../dialect';

/**
 * alterColumn identity 四态专项用例（spec §8）。
 *
 * 离线断言 MigrateBuilder.alterColumn 在 identity 四态下生成的 DDL 文本：
 * - mssql: add/drop → RAISERROR 附指引（对齐 EF Core，不支持自动重建/侧迁）；
 *   reseed → DBCC CHECKIDENT；undefined（不变）→ 不发 identity 语句。
 * - mysql: add/reseed/keep → MODIFY ... AUTO_INCREMENT；drop → 无 AUTO_INCREMENT；
 *   reseed 额外 ALTER TABLE ... AUTO_INCREMENT = n。
 *
 * 不连库，仅验证 DDL 生成正确性。
 */
describe('alterColumn identity 四态 [P0]', function () {
  const db = getProvider();
  const mb = db.getMigrateBuilder();
  const sqlifier = (db as any).sqlifier;

  function sqlify(ret: any): string[] {
    const arr = Array.isArray(ret) ? ret : [ret];
    return arr.map((s) => (sqlifier.sqlify(s) as SqlCommand).sql);
  }

  function alter(action: 'add' | 'reseed' | 'drop' | 'keep'): string[] {
    const ret = mb.alterColumn('t_id', (g: any) => {
      const c = g('id', DbType.int32);
      if (action === 'add') {
        c.identity(100, 1);
      } else if (action === 'drop') {
        c.dropIdentity();
      } else if (action === 'reseed') {
        c.$identityAction = 'reseed';
        c.$identitySeed = { startValue: 100, increment: 1 };
      }
      // keep: 不设任何 identity 字段
      return c;
    });
    return sqlify(ret);
  }

  if (adapter.driver === 'mssql') {
    it('[P0] add identity → RAISERROR（不支持自动加 identity）', () => {
      const sqls = alter('add');
      const all = sqls.join('\n');
      assert(
        all.includes('RAISERROR'),
        `mssql add identity 应发 RAISERROR，实际: ${all}`
      );
      assert(/加 identity/.test(all), `应附"加 identity"指引，实际: ${all}`);
    });

    it('[P0] drop identity → RAISERROR（不支持自动去 identity）', () => {
      const sqls = alter('drop');
      const all = sqls.join('\n');
      assert(
        all.includes('RAISERROR'),
        `mssql drop identity 应发 RAISERROR，实际: ${all}`
      );
      assert(/去 identity/.test(all), `应附"去 identity"指引，实际: ${all}`);
    });

    it('[P0] reseed → DBCC CHECKIDENT', () => {
      const sqls = alter('reseed');
      const all = sqls.join('\n');
      assert(
        /DBCC\s+CHECKIDENT/i.test(all),
        `mssql reseed 应发 DBCC CHECKIDENT，实际: ${all}`
      );
      assert(all.includes('100'), `DBCC 应含种子值 100，实际: ${all}`);
    });

    it('[P0] keep（不变）→ 不发 identity 语句', () => {
      const sqls = alter('keep');
      const all = sqls.join('\n');
      assert(
        !/RAISERROR|DBCC\s+CHECKIDENT/i.test(all),
        `mssql identity 不变不应发 RAISERROR/DBCC，实际: ${all}`
      );
    });
  }

  if (adapter.driver === 'mysql') {
    it('[P0] add identity → MODIFY ... AUTO_INCREMENT', () => {
      const sqls = alter('add');
      const all = sqls.join('\n');
      assert(
        /AUTO_INCREMENT/i.test(all),
        `mysql add identity 应含 AUTO_INCREMENT，实际: ${all}`
      );
    });

    it('[P0] drop identity → MODIFY 无 AUTO_INCREMENT', () => {
      const sqls = alter('drop');
      const all = sqls.join('\n');
      assert(
        !/AUTO_INCREMENT/i.test(all),
        `mysql drop identity 不应含 AUTO_INCREMENT，实际: ${all}`
      );
    });

    it('[P0] reseed → AUTO_INCREMENT + AUTO_INCREMENT = n', () => {
      const sqls = alter('reseed');
      const all = sqls.join('\n');
      assert(
        /MODIFY COLUMN.*AUTO_INCREMENT/i.test(all),
        `mysql reseed MODIFY 应含 AUTO_INCREMENT，实际: ${all}`
      );
      assert(
        /AUTO_INCREMENT\s*=\s*100/i.test(all),
        `mysql reseed 应发 AUTO_INCREMENT = 100，实际: ${all}`
      );
    });

    it('[P0] keep（不变，带 $identitySeed）→ MODIFY 保留 AUTO_INCREMENT', () => {
      // scripter 在 identity 不变时设 $identitySeed（无 action），mysql 据此保留 AUTO_INCREMENT
      const ret = mb.alterColumn('t_id', (g: any) => {
        const c = g('id', DbType.int32);
        c.$identitySeed = { startValue: 1, increment: 1 };
        return c;
      });
      const all = sqlify(ret).join('\n');
      assert(
        /AUTO_INCREMENT/i.test(all),
        `mysql identity 不变应保留 AUTO_INCREMENT，实际: ${all}`
      );
    });
  }

  if (adapter.driver === 'pgsql') {
    // pgsql identity 四态 + I1 回归守卫(identity 列不得发 DROP DEFAULT,
    // pg 显式 DROP/SET DEFAULT 均报错 "is an identity column")。
    it('[P0] add identity → ADD GENERATED BY DEFAULT AS IDENTITY', () => {
      const sqls = alter('add');
      const all = sqls.join('\n');
      assert(
        /ADD\s+GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY/i.test(all),
        `pgsql add identity 应含 ADD GENERATED BY DEFAULT AS IDENTITY,实际: ${all}`
      );
      assert(
        !/DROP\s+DEFAULT/i.test(all),
        `pgsql add identity 列不应发 DROP DEFAULT(I1),实际: ${all}`
      );
    });

    it('[P0] drop identity → DROP IDENTITY', () => {
      const sqls = alter('drop');
      const all = sqls.join('\n');
      assert(
        /DROP\s+IDENTITY/i.test(all),
        `pgsql drop identity 应含 DROP IDENTITY,实际: ${all}`
      );
      assert(
        !/DROP\s+DEFAULT/i.test(all),
        `pgsql drop identity 列不应发 DROP DEFAULT(I1),实际: ${all}`
      );
    });

    it('[P0] reseed → RESTART WITH 100', () => {
      const sqls = alter('reseed');
      const all = sqls.join('\n');
      assert(
        /RESTART\s+WITH\s+100/i.test(all),
        `pgsql reseed 应含 RESTART WITH 100,实际: ${all}`
      );
      assert(
        !/DROP\s+DEFAULT/i.test(all),
        `pgsql reseed identity 列不应发 DROP DEFAULT(I1),实际: ${all}`
      );
    });

    it('[P0] keep(identity 不变,带 $identitySeed)→ 不发 identity 语句,不发 DROP DEFAULT', () => {
      // scripter 在 identity 不变时设 $identitySeed(无 action):pgsql 据此跳过 DROP DEFAULT
      // (keep 列仍为 identity,DROP 会报错),且 action undefined 不发任何 identity 语句。
      const ret = mb.alterColumn('t_id', (g: any) => {
        const c = g('id', DbType.int32);
        c.$identitySeed = { startValue: 1, increment: 1 };
        return c;
      });
      const all = sqlify(ret).join('\n');
      assert(
        !/ADD\s+GENERATED|DROP\s+IDENTITY|RESTART\s+WITH/i.test(all),
        `pgsql identity 不变不应发 identity 语句,实际: ${all}`
      );
      assert(
        !/DROP\s+DEFAULT/i.test(all),
        `pgsql identity 不变(keep)不应发 DROP DEFAULT(I1 关键守卫),实际: ${all}`
      );
    });

    it('[P0] 非 identity 列 → 发 DROP DEFAULT(确认 I1 fix 不过度抑制)', () => {
      // 无 identity 字段且无 $default:应正常发 DROP DEFAULT(对齐 mssql 语义)。
      const sqls = alter('keep');
      const all = sqls.join('\n');
      assert(
        /DROP\s+DEFAULT/i.test(all),
        `pgsql 非 identity 列应发 DROP DEFAULT,实际: ${all}`
      );
    });
  }

  if (adapter.driver === 'sqlite') {
    // sqlite identity:add/drop 抛错(AUTOINCREMENT 必须建表期声明,不支持在线增删);
    // reseed 走 UPDATE sqlite_sequence;keep(undefined)不发 identity 语句。
    it('[P0] add identity → 抛错(sqlite 不支持后加 AUTOINCREMENT)', () => {
      assert.throws(
        () => alter('add'),
        /ADD\s+IDENTITY\s+not\s+supported\s+in\s+sqlite/i,
        `sqlite add identity 应抛错,实际: 未抛错`
      );
    });

    it('[P0] drop identity → 抛错(对齐 add;sqlite 删 AUTOINCREMENT 需表重建)', () => {
      assert.throws(
        () => alter('drop'),
        /DROP\s+IDENTITY\s+not\s+supported\s+in\s+sqlite/i,
        `sqlite drop identity 应抛错,实际: 未抛错`
      );
    });

    it('[P0] reseed → UPDATE sqlite_sequence', () => {
      const ret = mb.alterColumn('t_id', (g: any) => {
        const c = g('id', DbType.int32);
        c.$identityAction = 'reseed';
        c.$identitySeed = { startValue: 100, increment: 1 };
        return c;
      });
      const all = sqlify(ret).join('\n');
      assert(
        /UPDATE\s+sqlite_sequence\s+SET\s+seq\s*=\s*100/i.test(all),
        `sqlite reseed 应含 UPDATE sqlite_sequence SET seq = 100,实际: ${all}`
      );
    });

    it('[P0] keep(identity 不变)→ 不发 identity 语句', () => {
      const sqls = alter('keep');
      const all = sqls.join('\n');
      assert(
        !/AUTOINCREMENT|sqlite_sequence|IDENTITY/i.test(all),
        `sqlite identity 不变不应发 identity 语句,实际: ${all}`
      );
    });
  }
});
